# Generated by Django 2.1.4 on 2019-01-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(default='a', max_length=5)),
                ('gstid', models.CharField(default=None, max_length=15)),
                ('date', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('pic', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('qty', models.FloatField()),
                ('measurement_type', models.CharField(default='None', max_length=5)),
                ('category_type', models.CharField(default='None', max_length=2)),
                ('cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('expirity_date', models.CharField(default=None, max_length=20, null=True)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
    ]
